package Practice;/* Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair of element from the array.
Note: AND is bitwise '&' operator.*/

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.Scanner;

public class MaxAND {

    public static void main(String[] args) throws Exception {
        int i;
        System.out.println("Please enter the value of n");
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        int n = Integer.parseInt(br.readLine().trim());
        String[] StringArray = br.readLine().trim().split(" ");
        int[] arr = new int[n];
        for (i = 0; i < n; i++) {
            arr[i] = Integer.parseInt(StringArray[i]);
        }
        maxANDValue(arr);
        int max = 0;
        for (int k : arr) {

            for (int l : arr) {
                if ((k & l) > max) {
                    max = (k & l);
                }
            }
        }

    }


    public static void check(int[] arr) {

    }


    public static void maxANDValue(int[] arr) {

        int pattern = 0, n, i, count, j;
        n = 1;

        for (i = 31; i >= 0; i--) {
            n = n << i;
            count = 0;
            for (j = 0; j < arr.length; j++) {
                if ((n & arr[j]) > 0 && ((pattern & arr[j]) == pattern)) {
                    count++;
                }
            }
            if (count >= 2) {
                pattern |= n;

            }
            n = 1;
        }
        System.out.println(pattern);
    }
}


